@token=4|aL2DMpJckVolrLzXQFfvRBSmeg5IJZReUMpWffDiac07d06e
POST http://localhost:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email":"sergio@example.com",
    "password":"sergio54321"
}
###
POST http://localhost:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name":"sergio",
    "email":"sergio@example.com",
    "password":"sergio54321",
    "cpassword":"sergio54321"
}
###
GET http://localhost:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer {{token}}
###
POST http://localhost:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer {{token}}
