### List all
GET http://localhost:8000/api/category
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json
### Create one
POST http://localhost:8000/api/category
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json
Content-Type: application/json

{
    "name":"Casdfaasdfrsadfs",
    "detail":"Model 2010's"
}
### Show One
GET http://localhost:8000/api/category/1
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json

### Update one
PUT http://localhost:8000/api/category/2
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json
Content-Type: application/json

{
    "name":"Toys (UPDATED)",
    "detail":"For kids"
}

### DELETE
DELETE http://localhost:8000/api/category/4
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json