### List all 
GET http://localhost:8000/api/note
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
### Create|PURCHASE 
POST http://localhost:8000/api/note
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "note_type":"purchase",
    "taxes":0,
    "discounts":0,
    "total_calculated":0,
    "note_state": "note_state",
    "observations": "observations",
    "client_id":1,
    "user_id":1,
    "movements":[
        {"product_id":1,"storehouse_id":1,"quantity":5,"movement_type":"entry","unit_purchase_price":1200,"unit_sales_price":1300,"observations":"none"},
        {"product_id":2,"storehouse_id":1,"quantity":10,"movement_type":"entry","unit_purchase_price":4000,"unit_sales_price":4500,"observations":"none"}
    ]
}
### Create|SALE 
POST http://localhost:8000/api/note
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "note_type":"sale",
    "taxes":0,
    "discounts":0,
    "total_calculated":0,
    "note_state": "note_state",
    "observations": "observations",
    "client_id":1,
    "user_id":1,
    "movements":[
        {"product_id":1,"storehouse_id":1,"quantity":5,"movement_type":"exit","unit_purchase_price":1200,"unit_sales_price":1300,"observations":"none"},
        {"product_id":2,"storehouse_id":1,"quantity":3,"movement_type":"exit","unit_purchase_price":4000,"unit_sales_price":4500,"observations":"none"}
    ]
}
### Update one 

### Find one 
GET http://localhost:8000/api/note/4
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
### Delete 
DELETE http://localhost:8000/api/note/3
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
### pdfReport
GET http://localhost:8000/api/note/pdfReport
Accept: application/json
#Authorization: Bearer {{$dotenv TOKEN}}