### User's endpoints ###
### List
GET http://localhost:8000/api/users
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
### Save
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "name": "borrar",
    "email": "borrar@example.com",
    "password": "borrar54321"
}
### ShowOne
GET http://localhost:8000/api/users/1
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}
### Edit
PUT http://localhost:8000/api/users/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "name": "josemaria",
    "email": "josemaria@example.com",
    "password": "josemaria54321"
}
### Delete
DELETE http://localhost:8000/api/users/7/delete
Accept: application/json
Authorization: Bearer {{$dotenv TOKEN}}